FROM oven/bun:1.3.2 AS builder
WORKDIR /app

COPY package.json bun.lock turbo.json ./
COPY app/api/package.json app/api/
COPY app/web/package.json app/web/

RUN bun install --frozen-lockfile

COPY . .

RUN bun run build --filter=web

FROM nginx:1.27-alpine AS runner
WORKDIR /usr/share/nginx/html

COPY app/web/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/app/web/dist ./

EXPOSE 80
